<a href="https://colab.research.google.com/github/nefetorve/Advent-of-Code/blob/main/2021/day_3/day_3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import pandas as pd
test = ["00100", "11110", "10110", "10111", "10101", "01111", "00111", "11100", "10000", "11001", "00010", "01010"]
with open('input.txt') as f:
    test = f.read().splitlines()
test_as_values = []
len_test = len(test)

for element in test:
  test_as_values.append((list(element)))
df = pd.DataFrame(test_as_values).astype(int)
df_copy_oxygen  = df.copy()

In [127]:
rows = len(df_copy_oxygen) 
cols =  len(df_copy_oxygen.columns)
i = 0 
while i!=cols: 
  check = int(len(df_copy_oxygen))
  mask = (df_copy_oxygen.sum()/check>=0.5)
  print(mask,check)
  if mask[i] == True: 
    df_copy_oxygen= df_copy_oxygen.drop(df_copy_oxygen.loc[df_copy_oxygen[i]==0].index, inplace=False)
  elif mask[i] == False:
    df_copy_oxygen = df_copy_oxygen.drop(df_copy_oxygen.loc[df_copy_oxygen[i]==1].index, inplace=False)
  i+=1
  rows = len(df_copy_oxygen)

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
dtype: bool 1000
0      True
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9      True
10     True
11    False
dtype: bool 506
0      True
1     False
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9      True
10     True
11    False
dtype: bool 256
0      True
1     False
2      True
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
dtype: bool 130
0      True
1     False
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11    False
dtype: bool 76
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11    False
dtype: bool 45
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11     True
dtype: bool 25
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11     True
dtype: bool 14
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11    False
dtype: bool 9
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11     True
dtype: bool 6
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11    False
dtype: bool 3
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11     True
dtype: bool 2

In [128]:
df_copy_co2  = df.copy()
rows = len(df_copy_co2) 
cols =  len(df_copy_co2.columns)
i = 0 
while i!=cols: 
  check = int(len(df_copy_co2))
  mask = (df_copy_co2.sum()/check>=0.5)
  print(mask,check)
  if len(df_copy_co2) == 1:
    break
  if mask[i] == True: 
    df_copy_co2= df_copy_co2.drop(df_copy_co2.loc[df_copy_co2[i]==1].index, inplace=False)
  elif mask[i] == False:
    df_copy_co2 = df_copy_co2.drop(df_copy_co2.loc[df_copy_co2[i]==0].index, inplace=False)
  i+=1
  rows = len(df_copy_co2)

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
dtype: bool 1000
0     False
1     False
2      True
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10    False
11     True
dtype: bool 494
0     False
1      True
2     False
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
dtype: bool 237
0     False
1      True
2      True
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
dtype: bool 116
0     False
1      True
2      True
3      True
4     False
5     False
6      True
7      True
8      True
9      True
10     True
11     True
dtype: bool 55
0     False
1      True
2      True
3      True
4      True
5     False
6      True
7      True
8     False
9      True
10     True
11     True
dtype: bool 26
0     False
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8     False
9      True
10    False
11     True
dtype: bool 11
0     False
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8      True
9      True
10    False
11     True
dtype: bool 5
0     False
1      True
2      True
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10    False
11     True
dtype: bool 2
0     False
1      True
2      True
3      True
4      True
5      True
6     False
7      True
8     False
9      True
10    False
11     True
dtype: bool 1

In [129]:
oxygen = df_copy_oxygen.values
co2 = df_copy_co2.values
binary_to_decimal = [2**x for x in range(len(oxygen[0])-1,-1, -1)]

In [130]:
decimal_oxygen = []
decimal_co2 = []
for idx,binary in enumerate(binary_to_decimal):
  values_oxygen= binary*oxygen[0][idx]
  decimal_oxygen.append(values_oxygen)
  values_co2 = binary*co2[0][idx]
  decimal_co2.append(values_co2)

In [131]:
sum(decimal_co2) * sum(decimal_oxygen)

5852595